# Configuration pour la base de données
spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:

  # Configuration pour JPA / Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

   # Configuration batch
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

# Configuration du serveur
server:
  port: 9090

